name: Spring Boot CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3️⃣ Cache Maven dependencies (faster builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build & run tests
      - name: Build with Maven and run tests
        run: mvn clean verify

      # 5️⃣ Build Docker image (optional, for Render)
      - name: Build Docker image
        run: docker build -t diary-backend .

      #  Optionally, you could push Docker image to a registry if needed
      # - name: Push Docker image
      #   run: docker push <your-dockerhub-or-other-registry>
